
services:
  postgres:
    image: ankane/pgvector
    container_name: chatbot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatbot_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: chatbot_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adminexample@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - chatbot_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/dbconnection.env
    networks:
      - chatbot_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - chatbot_network
    restart: unless-stopped

volumes:
  pg_data:

networks:
  chatbot_network:
