
FROM python:3.12.9-slim-bookworm

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY .streamlit/config.toml /root/.streamlit/config.toml

CMD ["streamlit", "run", "chatbot_ui.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.enableCORS=false"]
